### ISSUE TITLE
Login for Authorization

### ISSUE THREAD

**Issue by andrusha19** [Geoalert/urban-mapping#12]
In API documentation you say:
"You can query our "Urban Mapping" data via the endpoint: http://demo.geoalert.io/russia-buildings/geojson?.
! Authorization via Basic Auth is required."

But what kind of login/password should I provide? On  http://demo.geoalert.io site I can log in using only google account. But this credentials doesn't work for API.

**Comment by Godnik** [comment]
@andrusha19 sorry, this API was deprecated. We star publishing open datasets as files.
The new API allows you to start processing on the side of our platform. It's going to be released publicly next month

**Comment by zhuang-hao-ming** [comment]
@Godnik Hello, is the api open? Is there a way to query all Russian data?
We hope to use these data to do some promising research.

**Comment by GregNed** [comment]
> @Godnik Hello, is the api open? Is there a way to query all Russian data?
> We hope to use these data to do some promising research.

@zhuang-hao-ming Hello, thanks for your interest. The API isn't open yet, for now, we'll be releasing the data as archives in this repo. So far, we have only been able to publish two regions: [Chechnya](https://bit.ly/30voBD4) & [Tyva](https://bit.ly/3lEh6l8). Validation of the results takes time, and we'll be publishing more regions as we proceed with it.

**Comment by zhuang-hao-ming** [comment]
@GregNed 
Thank you very much for your reply.
Is it possible to provide raw data, through cooperation or service purchase, we are very interested in this data, although we are a small research group, funds may be relatively limited. Thank you.

**Comment by GregNed** [comment]
@zhuang-hao-ming Sure, let's continue via email if you don't mind. I just sent you an email from hello@geoalert.io which is our corporate email address. My colleagues and I will be glad to discuss the matter.

**Comment by zhuang-hao-ming** [comment]
@GregNed  
Of course, I have replied to hello@geoalert.io, and look forward to your message.
